Template project
TanviKumar/generative-art pull request #3
Opened 2020-12-20 17:58 UTC by rt1301

I have added dat.gui library functions to most of the art pieces. This gives the user ability to play around with some parts of the code and see the corresponding changes immediately.
Screenshot of Change:
![Screenshot from 2020-12-20 17-03-13](https://user-images.githubusercontent.com/63252510/102720507-c3e97600-431a-11eb-80a0-17405a06b202.png)
![Screenshot from 2020-12-20 17-03-39](https://user-images.githubusercontent.com/63252510/102720511-c9df5700-431a-11eb-9d1b-e50bc36e72e8.png)

2021-01-23 17:29 UTC, Jayashrri requested changes

2021-01-23 17:29 UTC, Jayashrri commented on src/components/ArtDisplay/art-pieces/0_Template/sketch.js
> +          for (let x = padding; x < p.width - 2 * padding; x += cellSize + gap) {
`gap` hasn't been defined anywhere. This is raising an error.

2021-01-23 17:29 UTC, Jayashrri commented on src/components/ArtDisplay/art-pieces/PyramidGrid/sketch.js
> +  });
This is not getting animated.

2021-01-23 17:29 UTC, Jayashrri commented on src/components/ArtDisplay/art-pieces/HazyPyramids/sketch.js
> +  uiFrameRate.onChange(p.setup);
The frame rate doesn't seem to change on updating the selected value. Could you check once?

2021-01-23 17:29 UTC, Jayashrri commented on src/components/ArtDisplay/art-pieces/BeyondBinary/sketch.js
> +  };
You've used classes in the template, use that here too for uniformity?

2021-01-24 06:05 UTC, rt1301 commented on src/components/ArtDisplay/art-pieces/PyramidGrid/sketch.js
> +  });
This is actually a static drawing, hence you are not able to see any animation on changed framerate.

2021-01-24 06:11 UTC, rt1301 commented
@Jayashrri I have made the above-asked changes, please review them once. Thanks!

2021-01-24 08:45 UTC, Jayashrri approved these changes

2021-01-24 08:49 UTC, merged